<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>0e92d71b-beb4-4388-95c0-71c6a9897903</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.10" />
    <PackageReference Include="Microsoft.OpenApi" Version="2.12.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MarketPulse.Shared\MarketPulse.Shared.csproj" />
  </ItemGroup>

</Project>
